### ISSUE TITLE
Configurable `istanbulCLIOutput`

### ISSUE THREAD

**Issue by kachkaev** [anishkny/playwright-test-coverage#59]
👋 again @anishkny! WDYT of making `istanbulCLIOutput` configurable?

I mean changing

https://github.com/anishkny/playwright-test-coverage/blob/757e8f5e844565bd79dd909ba94793364b4fbaf5/index.js#L6

to something like:

```ts
const istanbulCLIOutput = process.env.ISTANBUL_CLI_OUTPUT
  ? path.resolve(process.env.ISTANBUL_CLI_OUTPUT)
  : path.join(process.cwd(), ".nyc_output");
```

This can potentially help in monorepos where `.nyc_output` is collected at the top level and Playwright tests run from a workspace.

`nyc` does not seem to support multiple  values for the`temp-dir` option. It’s still possible to copy files from a workspace to the monorepo root, but maybe using `ISTANBUL_CLI_OUTPUT` (or `ISTANBUL_TEMP_DIR`?) can be a bit more convenient. Not 100% sure though, just sharing thoughts 🙂

**Comment by anishkny** [comment]
This seems a good idea especially because it is opt-in.

Does this fix work in your specific monorepo use case? I am curious. If it helps I am okay adding it in!

**Comment by kachkaev** [comment]
I haven't tested the suggested snippet specifically, but I guess it would work. We’re planning to use a workaround in the meantime:

```yaml
     - name: Copy .nyc_output files from site to root
        ## https://github.com/anishkny/playwright-test-coverage/issues/59
        if: ${{ success() || failure() }}
        run: mv site/.nyc_output/* .nyc_output
```

Happy to test the PR diff before it gets merged!
